services:
  db:
    image: postgres:16
    container_name: db_project_task_board
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: project-task-board
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - project-task-board

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server_project_task_board
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/project-task-board
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - db
    networks:
      - project-task-board

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_project_task_board
    ports:
      - "5174:80"
    depends_on:
      - server
    networks:
      - project-task-board

networks:
  project-task-board:
    driver: bridge

volumes:
  db_data:
